export default {
  transparent: {
    png: `data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAgAAAAICAYAAADED76LAAAAPUlEQVQoU2NkQAX/oVxGmDCcwcDAAJJshErUMzAwgOXQFSCbh1UBTAPINNIUwHUg2QEWwzASlwKQOFZfAACTvg4JThfidAAAAABJRU5ErkJggg==`,
    webp: `data:image/webp;base64,UklGRlQAAABXRUJQVlA4WAoAAAAQAAAABwAABwAAQUxQSBUAAAABDzD/ERGCMNs4pnEAxbjXIvofcwoAVlA4IBgAAAAwAQCdASoIAAgAAUAmJaQAA3AA/v02aAA=`,
  },
  jpeg: `data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAMCAgICAgMCAgIDAwMDBAYEBAQEBAgGBgUGCQgKCgkICQkKDA8MCgsOCwkJDRENDg8QEBEQCgwSExIQEw8QEBD/2wBDAQMDAwQDBAgEBAgQCwkLEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBAQEBD/wAARCAAIAAgDASIAAhEBAxEB/8QAFQABAQAAAAAAAAAAAAAAAAAAAAj/xAAfEAABAwMFAAAAAAAAAAAAAAAUABMVBRYYBBIXJCX/xAAUAQEAAAAAAAAAAAAAAAAAAAAA/8QAFBEBAAAAAAAAAAAAAAAAAAAAAP/aAAwDAQACEQMRAD8ApGGqOQeQ111V/k6x7Va0sjFRII+1gtoz2xihQO+06iIg/9k=`,
  webp: `data:image/webp;base64,UklGRmoAAABXRUJQVlA4IF4AAAAwAgCdASoIAAgAAUAmJaQAEMAco7/QC2G9qAD+8pP/ijuZfG//yK7HQtB9kPDX/YB68P/G1iyPL//x26/U35/XfDX/ZiHdm5f/QV3232/Zo/KT//0Fd939v2QgAAAA`,
  png: `data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAgAAAAICAYAAADED76LAAAAO0lEQVQoU2P8////fwYoYGRkBLOQhBgYYQpAkjAJFDayAphJyKaQZgJOK5DtRHYwSAPYCoIKQLpw+QIARG9J6d2oAVYAAAAASUVORK5CYII=`,
}
